version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    assignees:
      - "GuillaumeOj"
  - package-ecosystem: "pub"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    assignees:
      - "GuillaumeOj"
