name: wod_board_app
description: "Smartphone app for Wod Board"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  basic_utils: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - .env
