services:
  db-tests:
    container_name: wod-board-db-tests
    image: postgres:latest
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: wod_board_tests
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    ports:
      - 6544:5432

volumes:
  postgres_data_test:
