services:
  db-dev:
    container_name: wod-board-db
    image: postgres:latest
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6543:5432

volumes:
  postgres_data:
