name: Workout log app
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
      - name: Create fake .env file
        run: touch .env
      - name: Run lint checks
        run: flutter analyze
  ci-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flutter
        uses: subosito/flutter-action@v2
      - name: Create fake .env file
        run: touch .env
      - name: Run tests
        run: flutter test

